silverstripe/silverstripe-postgresql

code/PostgreSQLDatabaseConfigurationHelper.php

If you can log in to postgresql (with write permissons), you can alter tables. This fixes the installer to reflect that this is the case.

Fixes "alter table" problem when installing.

---

code/PostgreSQLDatabase.php

A bug exist where a space in the default value for an enum field-type would result in no database update to happen for that field-type.
The bug can be replicated below.
Inside a class e.g. Page.php add the following Enum field as follows:
```php
private static $db = array(
'Enum' => "Enum('lorem,ip sum,dolor,sit,amet,consectetur', 'amet')"
);
```
A dev/build would result in the following three new fields:
* Page                                                                                                                                                                       
+ Field Page.Enum: created as varchar(255) default 'amet' check ("Enum" in ('lorem', 'ip sum', 'dolor', 'sit', 'amet', 'consectetur'))                                      
+ Field Page_Live.Enum: created as …

FIX allow for spaces in enum field-type default values

---

code/PostgreSQLDatabase.php

Relates to this issue: https://github.com/silverstripe/silverstripe-postgresql/issues/27
This issue causes pagination to fail for search results on sites
using the postgres db.
Patch corrects the TotalItems in the returned List to show all items
matching the search criteria rather than just the items returned in
the current 'page' requested.

FIX Total Items count on Search

---

.travis.yml
code/PostgreSQLSchemaManager.php

This is one of the worst fixes I've ever had to track down.
Because for some reason the postgres connector decided it can't handle floating point numbers.

BUG Fix decimal not supporting non-integer values

---

code/PostgreSQLSchemaManager.php

in postgresql, multiple schemas can exist within a single database, so in order to check for constraints (for instance, enum constraint on allowed values) you must always query against the schema.
Some whitespace issues rebasing against the PSR-2 cleaned up version of master, so probably best viewed with ?w=1 on the querystring.
https://github.com/silverstripe/silverstripe-postgresql/pull/48/files?w=1

BUG Fix constraints ignoring schema

---

code/PostgreSQLQuery.php

`pg_result_seek()` returns a boolean instead of the record: http://php.net/manual/en/function.pg-result-seek.php

FIX: PostgreSQLQuery::seek() failed to return a row

---

code/PostgreSQLQuery.php

derp 😅. Without the indexed array it’s useless, as we don’t know what the columns are!

FIX: PostgreSQLQuery::seek() returning indexed array instead of associative

---

.travis.yml
code/PostgreSQLQueryBuilder.php
tests/PostgreSQLQueryBuilderTest.php

required for https://github.com/silverstripe/silverstripe-framework/pull/6939/
cc @dhensby

API Ensure table aliases longer than max characters are safely re-written

---

.travis.yml

Now that we have support for PHP7 in SS 3.x, we should test the Postgres module against it.
I've set up the tests to run weekly on this branch (and master) via TravisCI new cron job feature.
While we have a nightly "all modules" run in silverstripe-installer, it doesn't have the same matrix coverage as this run here.
I've also removed removed tests against older (and unsupported) 3.x releases (it was testing against 3.2)

Testing in PHP7

---

code/PostgreSQLConnector.php

I've run into an issue in my load balanced environment that causes primary key duplicates. I believe this is because getGeneratedID() will return the last ID from an insert statement across all sessions, rather than just the session that did the insert. 
currval() looks to be the recommended way if you can't have "RETURNING ID" in your insert statement. As the "RETURNING ID" would be a major change, changing it to currval() would fix concurrency issues without major changes.

getGeneratedID to use currval() which is session dependent

---

.editorconfig
.scrutinizer.yml
.travis.yml
code/PostgreSQLDatabase.php
code/PostgreSQLSchemaManager.php
composer.json
phpcs.xml.dist
phpunit.xml.dist
tests/PostgreSQLConnectorTest.php
tests/PostgreSQLDatabaseTest.php
tests/PostgreSQLQueryBuilderTest.php

Includes postgres fix for https://github.com/silverstripe/silverstripe-framework/pull/7605 (non-nullable enum types)
Also adds linting to the module to match framework conventions.
PostgreSQL + PDO also wasn't working due to buggy fulltextsearch index parsing; Fixed this.
When using PDOConnector, postgres couldn't include multiple statements in a single query, so this has been split out into separate ->query() calls.
extractTriggerColumns() was not querying against the correct schema / database / table, so this has been added to the condition via a safe join.

BUG Fix 4.0.0 compat / PDO not working

---

code/PostgreSQLQuery.php

Noticed this bug.
The database was returning booleans as the strings `"t"` or `"f"`. The f is being coerced to 0, but so was t. This coerces t to 1.

FIX: Boolean ’t’/‘f’ strings need to be coerced to int properly.

---

code/PostgreSQLQuery.php

Fixes https://github.com/silverstripe/silverstripe-framework/issues/9097
Related: https://github.com/silverstripe/silverstripe-framework/issues/9098

FIX: Don’t drop first row on repeated iteration

---

.travis.yml

PostgreSQL 2.3+, like Framework 4.5+, is able to be PHP 7.1+. Updated
the test matrix to reflect this.

NEW: Drop PHP 5.6 testing

---

_register_database.php

The pre-check for PostgreSQL needs to look for pgsql and changed the
error text to link to the PostgreSQL PDO documentation instead of the
Microsoft SQL Server documentation.

Updated PDO PostgreSQL Check

---

.travis.yml
code/PostgreSQLSchemaManager.php
tests/PostgreSQLSchemaManagerTest.php

This is a work in progress. I fix the initial problem that prevented ClassNames from being migrated.
But there'smore problems with Versioned tables ClassName columns ... and potentially with Polymorphic relationships.
* https://github.com/silverstripe/silverstripe-framework/issues/8344

BUG Fix issues preventing a site from being migrated from SS3 to SS4

---

README.md

Moving from https://docs.silverstripe.org/en/4/getting_started/server_requirements/
since it's too much noise there.
Also removing the maintainer contact, that's an outdated concept.

DOCS Known issue about collations

---

code/PostgreSQLDatabaseConfigurationHelper.php

In addition to the pre-check for PostgreSQL needing to use pgsql
as the module name, the connection generator helper also needed
to be updated.
I missed this when submitting the last request #94 that only fixed the pre-check.

Updated PDO PostgreSQL Connection Creation

---

code/PostgreSQLQuery.php
composer.json

At the moment if you try to iterate over the result set many times all subsequent calls after the first won't return any rows.
This should fix a currently failing test in master

FIX Allow repeat calls to `getIterator()`

---

code/PostgreSQLSchemaManager.php

Issue https://github.com/silverstripe/silverstripe-framework/issues/10278
Travis deprecation warning https://app.travis-ci.com/github/silverstripe/silverstripe-installer/jobs/567049880#L1356
I'm not sure if this will also fix the database related travis failures

FIX Ignore invalid byte character

---

.travis.yml
composer.json

Issue https://github.com/silverstripeltd/product-issues/issues/550
While broken build in on `2`, makes sense to target `2.3` as these are dev only changes

MNT Test using PHPUnit9
